name: Build Executable

on:
  push:
    branches:
      - master # Adjust branch as needed
  pull_request:
    branches:
      - master # Adjust branch as needed

jobs:
  build-linux:
    runs-on: ubuntu-latest # Use ubuntu-latest for cross-platform compatibility

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
        #   pip install -r requirements.txt  # Adjust as per your project setup

      - name: Build executable
        run: |
          python -m pip install pyinstaller
          pyinstaller --onefile --windowed main.py  # Replace with your main script name

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: exe-files
          path: dist # Assuming 'dist' is the default directory pyinstaller creates the exe in

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0 # Replace with your desired tag version
          release_name: Release v1.0.0 # Replace with your desired release name
          body: |
            Release notes for version 1.0.0
            - Added executable files for Windows, macOS, and Linux
          draft: false
          prerelease: false
          files: dist/*.exe # Upload the .exe files as release assets

  # Repeat the build job for Windows and macOS if needed
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
        #   pip install -r requirements.txt

      - name: Build executable
        run: |
          python -m pip install pyinstaller
          pyinstaller --onefile --windowed main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: exe-files-windows
          path: dist

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
        #   pip install -r requirements.txt

      - name: Build executable
        run: |
          python -m pip install pyinstaller
          pyinstaller --onefile --windowed main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: exe-files-macos
          path: dist

  create-release:
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - build-macos
      - build-windows
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0 # Replace with your desired tag version
          release_name: Release v1.0.0 # Replace with your desired release name
          body: |
            Release notes for version 1.0.0
            - Added executables for Windows, macOS, and Linux
          draft: false
          prerelease: false

      - name: Download Release Assets
        uses: dawidd6/action-download-artifact@v2
        with:
          name: exe-files
          path: dist

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist
          asset_name: exe-files
          asset_content_type: application/zip
